version: '2'
services:
  web:
    image: apachephp:5.6
    networks:
      symf_net:
        ipv4_address: 172.18.20.09
    #extra_hosts:
    #- "localhost:127.0.0.1"
    expose:
    - "9000"
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./src:/var/www/html
    - ~/.ssh:/home/magento2/.ssh
    - ./apache_vhost:/etc/apache2/sites-available/
    environment:
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_CONFIG: remote_host=172.18.20.1
      PHP_IDE_CONFIG: "serverName=Symfony"
    links:
    - mysql
    - broker
    container_name: ${PROJECT_NAME}_web
  mysql:
    image: mysql:5.7
    networks:
      symf_net:
        ipv4_address: 172.18.20.11
    volumes:
    - ./database/data:/var/lib/mysql
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    container_name: ${PROJECT_NAME}_db
  broker:
    image: rabbitmq:3-management
    networks:
      symf_net:
        ipv4_address: 172.18.20.10
    ports:
      - 15672:15672
    #volumes:
    #  - ./database/data:/var/lib/mysql
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    container_name: ${PROJECT_NAME}_broker
networks:
  symf_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.18.20.0/24
          gateway: 172.18.20.1