app_logout:
  path: /logout

dtc_queue:
  resource: '@DtcQueueBundle/Resources/config/routing.yml'
dtc_grid:
  resource: '@DtcGridBundle/Resources/config/routing.yml'
#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_lucky_number:
  path: /lucky/number
  controller: App\Controller\LuckyController::number

blog_list:
  path:     /blog
  controller: App\Controller\BlogController::list

blog_show:
  path:     /blog/{slug}
  controller: App\Controller\BlogController::show